apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ujyl
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-ujyl@sha256:d0d3706a09044af7b2ef6988006aac289ceab2eee10fdcd6b6fc9a5a6e56d00d
        name: my-nodejs
        resources: {}
status: {}
